### ISSUE TITLE
Motion Sync with live 2d

### ISSUE THREAD

**Issue by antochan** [LazerCuber/Waifu-AI#5]
Hey lazercuber!

Any plans to add lip sync from cubism 5.0? 

p.s. Been following along with your progress with this AI concept. Would love to have a chat with you :)

**Comment by antochan** [comment]
@LazerCuber , how can I reach out to you outside GH? :)

**Comment by LazerCuber** [comment]
Hello there, sorry late reply. I've updated my github profile to include a link to my twitter account, in case you'd like to reach out to me there. :D

**Comment by antochan** [comment]
Just sent you a follow :) Im Mantou!
